# Generated by Django 4.1.1 on 2022-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='User'),
        ),
    ]
