# Generated by Django 4.1.1 on 2022-10-05 17:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
    ]
