# Generated by Django 4.1.1 on 2022-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0006_resume_author_delete_usersid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='adres',
            field=models.CharField(default='', max_length=50, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='resume',
            name='confirm_skills',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='', verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('ж', 'ж'), ('м', 'м')], default='', max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='', verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='resume',
            name='spec',
            field=models.CharField(default='', max_length=20, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='resume',
            name='type_of_employment',
            field=models.CharField(choices=[('Полная', 'Полная'), ('Частичная', 'Частичная'), ('Удалённо', 'Удалённо')], default='', max_length=20, verbose_name='type_of_employment'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(default='', max_length=3, verbose_name='age'),
        ),
    ]
