# Generated by Django 4.1.1 on 2022-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0007_resume_adres_resume_confirm_skills_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='salary'),
        ),
    ]
