# Generated by Django 4.1.1 on 2022-10-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0012_my_user_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_user',
        ),
    ]
