# Generated by Django 4.1.1 on 2022-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0014_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
