# Generated by Django 4.1.1 on 2022-10-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0015_alter_userstatus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('foundation_data', models.DateField(verbose_name='Foundation data')),
                ('industry', models.CharField(max_length=200, verbose_name='Industry')),
                ('strategy_description', models.TextField(verbose_name='Strategy Description')),
            ],
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('candidate', 'Ищу работу'), ('employer', 'Ищу работника'), ('top_employer', 'Подписка ПРО')], max_length=100),
        ),
    ]
