# Generated by Django 4.1.1 on 2022-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0016_companies_alter_userstatus_status'),
    ]
    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(max_length=200, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='strategy_description',
            field=models.TextField(null=True, verbose_name='Strategy Description'),
        ),
    ]
