# Generated by Django 4.1.1 on 2022-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0017_alter_companies_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(null=True, verbose_name='Foundation data'),
        ),
    ]
