# Generated by Django 4.1.1 on 2022-10-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0018_alter_companies_foundation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.date.today, verbose_name='Foundation data'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(default='Информация не заполнена', max_length=200, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='strategy_description',
            field=models.TextField(default='Информация не заполнена', verbose_name='Strategy Description'),
        ),
    ]
