# Generated by Django 4.1.1 on 2022-10-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0019_alter_companies_foundation_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Resume Name')),
                ('location', models.CharField(max_length=200, verbose_name='Locations')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('skills', models.CharField(max_length=200, verbose_name='skills')),
            ],
        ),
    ]
