# Generated by Django 4.1.1 on 2022-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0020_vacansies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Resume Name')),
                ('location', models.CharField(max_length=200, verbose_name='Locations')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('skills', models.CharField(max_length=200, verbose_name='skills')),
                ('salary', models.CharField(max_length=200, verbose_name='Salary')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacansies',
        ),
        migrations.AddField(
            model_name='companies',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='User Name'),
        ),
    ]
