# Generated by Django 4.1.1 on 2022-10-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0023_alter_vacancies_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='company_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.companies'),
        ),
    ]
