# Generated by Django 4.1.1 on 2022-10-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0031_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='skills',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='skills',
            field=models.ManyToManyField(to='my_hh_app.skills'),
        ),
    ]
