# Generated by Django 4.1.1 on 2022-10-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0034_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.companies'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='my_hh_app.skills'),
        ),
    ]
