# Generated by Django 4.1.1 on 2022-10-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_hh_app', '0035_responses_company_alter_vacancies_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsesVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(default='', verbose_name='Cover Letter')),
                ('author_vacancy_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resume_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.resume')),
                ('vacancy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.vacancies')),
            ],
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
    ]
