# Generated by Django 4.1.1 on 2022-10-16 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_hh_app', '0036_responsesvacancy_delete_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='confirm_skills',
        ),
        migrations.AlterField(
            model_name='companies',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(verbose_name='foundation_data'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(max_length=200, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='strategy_description',
            field=models.TextField(verbose_name='Strategy_description'),
        ),
        migrations.AlterField(
            model_name='responsesvacancy',
            name='cover_letter',
            field=models.TextField(verbose_name='Cover_letter'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='adres',
            field=models.CharField(max_length=200, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(max_length=3, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=200, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.CharField(max_length=200, verbose_name='salary'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='resume',
            name='spec',
            field=models.TextField(max_length=200, verbose_name='speciality'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type_of_employment',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], max_length=200, verbose_name='type_of_employment'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='is_checked',
            field=models.BooleanField(verbose_name='is_checked'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=200, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.companies'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(max_length=200, verbose_name='salary'),
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='skills',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.skills'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_hh_app.skills'),
        ),
    ]
