# Generated by Django 4.1.1 on 2022-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0037_remove_resume_author_remove_resume_confirm_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.CharField(max_length=200, verbose_name='user'),
        ),
    ]
