# Generated by Django 4.1.1 on 2022-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0039_resume_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='is_checked',
            field=models.BooleanField(null=True, verbose_name='is_checked'),
        ),
    ]
