# Generated by Django 4.1.1 on 2022-10-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_hh_app', '0041_alter_companies_foundation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='author',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default='', null=True, verbose_name='foundation_data'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='strategy_description',
            field=models.TextField(default='', null=True, verbose_name='Strategy_description'),
        ),
    ]
