# Generated by Django 4.1.1 on 2022-10-18 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0045_alter_companies_foundation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='IsRight',
            new_name='is_right',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='QuestionId',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ProfileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='DateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='ProfileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='UserName',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 7, 20, 34, 172172), null=True, verbose_name='foundation_data'),
        ),
    ]
