# Generated by Django 4.1.1 on 2022-10-18 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0046_rename_isright_answer_is_right_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Good',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Perfect',
            new_name='perfect',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='QuestionsCount',
            new_name='questions_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Statisfactorily',
            new_name='satisfactory',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='WorkTime',
            new_name='work_time',
        ),
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 7, 24, 47, 497923), null=True, verbose_name='foundation_data'),
        ),
    ]
