# Generated by Django 4.1.1 on 2022-10-18 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0047_rename_good_profile_good_rename_name_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 8, 27, 50, 460882), null=True, verbose_name='foundation_data'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='my_hh_app.skills'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='skills',
            field=models.ManyToManyField(to='my_hh_app.skills'),
        ),
    ]
