# Generated by Django 4.1.1 on 2022-10-18 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0049_alter_companies_foundation_data_usercheckedskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 8, 37, 12, 497410), null=True, verbose_name='foundation_data'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='is_checked',
            field=models.BooleanField(default='False', verbose_name='is_checked'),
        ),
    ]
