# Generated by Django 4.1.1 on 2022-10-18 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0050_alter_companies_foundation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 8, 51, 13, 784064), null=True, verbose_name='foundation_data'),
        ),
    ]
