# Generated by Django 4.1.1 on 2022-10-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0051_alter_companies_foundation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 9, 39, 48, 721797), null=True, verbose_name='foundation_data'),
        ),
    ]
