# Generated by Django 4.1.1 on 2022-10-18 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0053_alter_companies_foundation_data_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='checked_skills',
            field=models.ManyToManyField(to='my_hh_app.usercheckedskills'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 14, 41, 0, 419963), null=True, verbose_name='foundation_data'),
        ),
    ]
