# Generated by Django 4.1.1 on 2022-10-18 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hh_app', '0054_resume_checked_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='foundation_data',
            field=models.DateField(default=datetime.datetime(2022, 10, 18, 15, 53, 28, 974092), null=True, verbose_name='foundation_data'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='checked_skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='checked_skills',
            field=models.CharField(max_length=200, null=True, verbose_name='checked_skills'),
        ),
    ]
